# ==========================================
# CONFIGURACIÓN BÁSICA
# ==========================================
spring.application.name=pedido
server.port=8083

# ==========================================
# BASE DE DATOS MYSQL - AIVEN
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.datasource.hikari.initialization-fail-timeout=0

# ==========================================
# JWT
# ==========================================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ==========================================
# LOGS
# ==========================================
logging.level.com.syncro.pedido=DEBUG

# ==========================================
# RABBITMQ
# ==========================================
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST}

spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

# ==========================================
# PERFIL
# ==========================================
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=WARN
# ==========================================
# CIRCUIT BREAKER - RESILIENCE4J
# ==========================================
resilience4j.circuitbreaker.instances.rabbitmq.sliding-window-size=5
resilience4j.circuitbreaker.instances.rabbitmq.failure-rate-threshold=60
resilience4j.circuitbreaker.instances.rabbitmq.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.rabbitmq.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.rabbitmq.automatic-transition-from-open-to-half-open-enabled=true
